name: Laravel

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2

    - name: ssh scp ssh pipelines
      uses: cross-the-world/ssh-scp-ssh-pipelines@latest
      env:
        WELCOME: "ssh scp ssh pipelines"
        LASTSSH: "Doing something after copying"
      with:
        host: ${{ secrets.HOST }}
        user: ${{ secrets.USER }}
        key: ${{ secrets.KEY }}
        port: 22
        connect_timeout: 10s
        first_ssh: |         
          mkdir -p /home/sistemas/public_html/fabian
          chmod 755 /home/sistemas/public_html/fabian
          
        scp: |
          './*' => /home/sistemas/public_html/fabian
